<a href="https://colab.research.google.com/github/UTExDrake/AI_Basic/blob/main/Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
### Le Dang Khoa_20146497 ###
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import seaborn as sas
import numpy as np
import pandas as pd
data = pd.read_csv('lung_cancer_examples.csv')
data.head()
###--------------------------###
x = data.drop(['Name','Surname','Result'], axis = 1)
print(x[:5])
###--------------------------###
y = data.drop(['Name', 'Surname', 'Age', 'Smokes', 'AreaQ', 'Alkhol'], axis = 1)
print(y[:5])
###--------------------------###
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3)
sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)
print(x_train_std[:5])
print(y.T)
###--------------------------###
model = Perceptron(max_iter = 400, eta0= 1 , random_state = 0) #so lan train, toc do hoc
model.fit(x_train_std, y_train)
y_pred = model.predict(x_test_std)
print(y_pred[:10])
print(y_test[:10].T)
print("Do chinh xac cua mo hinh:", accuracy_score(y_test, y_pred))

   Age  Smokes  AreaQ  Alkhol
0   35       3      5       4
1   27      20      2       5
2   30       0      5       2
3   28       0      8       1
4   68       4      5       6
   Result
0       1
1       1
2       0
3       0
4       1
[[ 0.38319142 -0.17935746 -1.82562126  1.91617148]
 [ 0.19835791 -1.54114556  1.18560461 -0.94810568]
 [ 1.30735897  0.50153659 -0.10492076  1.09780658]
 [-0.97225431 -1.94968199 -0.10492076 -0.94810568]
 [-0.10969794 -0.17935746  0.75542949 -0.53892323]]
        0   1   2   3   4   5   6   7   8   9   ...  49  50  51  52  53  54  \
Result   1   1   0   0   1   0   0   0   0   1  ...   1   0   1   1   0   0   

        55  56  57  58  
Result   1   1   1   0  

[1 rows x 59 columns]
[1 0 0 1 0 0 1 1 1 1]
        29  38  5   18  58  2   48  24  28  20
Result   1   0   0   1   0   0   1   1   1   1
Do chinh xac cua mo hinh: 0.9444444444444444


/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
